const MenuAPI = [
    {
      id :1,
      image : "images/apple.png",
      name: "apple",
      Price: "$12",
      category:"fruit",
      des:"",
    },
    {
      id :2,
      image : "images/banana.png",
      name: "Banana",
      Price: "$6",
      category:"fruit",
      des:"",
    },
    {
      id :3,
      image : "images/carrot.png",
      name: "carrot",
      Price: "$12",
      category:"veg",
      des:"",
    },
    {
      id :4,
      image : "images/cabbage.png",
      name: "cabbage",
      Price: "$12",
      category:"veg",
      des:"",
    },
    {
      id :5,
      image : "images/beafsteak.png",
      name: " beaf steack",
      Price: "$12",
      category:"chicken",
      des:"",
    },
    {
      id :6,
      image : "images/bluegrapes.png",
      name: " bluegrapes",
      Price: "$19",
      category:"fruit",
      des:"",
    },
    {
      id :7,
      image : "images/cauliflower.png",
      name: " cauliflower",
      Price: "$5",
      category:"veg",
      des:"",
    },
    {
      id :8,
      image : "images/capsicum.png",
      name: " capsicum",
      Price: "$5",
      category:"veg",
      des:"",
    },
    {
      id :9,
      image : "images/chicken.png",
      name: " chicken",
      Price: "$5",
      category:"chicken",
      des:"",
    },

    {
      id :10,
      image : "images/lichi.png",
      name: " lichi",
      Price: "$60",
      category:"fruit",
      des:"",
    },
    {
      id :11,
      image : "images/orange.png",
      name: " orange",
      Price: "$5",
      category:"fruit",
      des:"",
    },
    {
      id :12,
      image : "images/tomato.png",
      name: " tomato",
      Price: "$5",
      category:"veg",
      des:"",
    },
    {
      id :13,
      image : "images/watermelon.png",
      name: " watermelon",
      Price: "$5",
      category:"fruit",
      des:"",
    },
    {
      id :14,
      image : "images/strawberry.png",
      name: "strawberry ",
      Price: "$5",
      category:"fruit",
      des:"",
    },
    {
      id :15,
      image : "images/cauliflower.png",
      name: " cauliflower",
      Price: "$5",
      category:"veg",
      des:"",
    },
    {
      id :16,
      image : "images/semon fish.png",
      name: " semon fish",
      Price: "$50",
      category:"chicken",
      des:"",
    },
    {
      id :17,
      image : "images/red papper.png",
      name: " red papper",
      Price: "$3",
      category:"veg",
      des:"",
    },
    {
      id :18,
      image : "images/green grapes.png",
      name: "green grapes",
      Price: "$30",
      category:"fruit",
      des:"",
    },
    
  ];

  export default MenuAPI;